version: '3.7'

services:

  landing: 
    image: nginx:latest
    volumes:
      - .:/usr/share/nginx/html
    network_mode: bridge
    restart: always
    ports:
      - "12000:80"
    labels:
    - traefik.frontend.rule=Host:www.bieccamvd.com,bieccamvd.com
    - traefik.docker.network=bridge
    - traefik.port=80